services:
  fintellect-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-5001}:${PORT:-5001}"
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - /app/node_modules
      - ./uploads:/app/uploads
    networks:
      - fintellect_network

  nexus-agent:
    build:
      context: ./server/nexus/agent
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - fintellect-server
    networks:
      - fintellect_network

networks:
  fintellect_network:
    driver: bridge 