export const MERCHANT_CATEGORIES: Record<string, string> = {
  // Food & Drink
  'mcdonalds': 'FOOD_AND_DRINK',
  'starbucks': 'FOOD_AND_DRINK',
  'subway': 'FOOD_AND_DRINK',
  'chipotle': 'FOOD_AND_DRINK',
  'dunkin': 'FOOD_AND_DRINK',
  'popeyes': 'FOOD_AND_DRINK',
  'wendys': 'FOOD_AND_DRINK',
  'burger king': 'FOOD_AND_DRINK',
  'taco bell': 'FOOD_AND_DRINK',
  'panera bread': 'FOOD_AND_DRINK',
  'dominos': 'FOOD_AND_DRINK',
  'pizza hut': 'FOOD_AND_DRINK',
  'kfc': 'FOOD_AND_DRINK',
  'chick-fil-a': 'FOOD_AND_DRINK',
  'five guys': 'FOOD_AND_DRINK',
  'dairy queen': 'FOOD_AND_DRINK',
  'arbys': 'FOOD_AND_DRINK',
  'papa johns': 'FOOD_AND_DRINK',
  'ihop': 'FOOD_AND_DRINK',
  'dennys': 'FOOD_AND_DRINK',

  // Shopping
  'amazon': 'SHOPPING',
  'walmart': 'SHOPPING',
  'target': 'SHOPPING',
  'costco': 'SHOPPING',
  'sams club': 'SHOPPING',
  'best buy': 'SHOPPING',
  'home depot': 'SHOPPING',
  'lowes': 'SHOPPING',
  'macys': 'SHOPPING',
  'kohls': 'SHOPPING',
  'marshalls': 'SHOPPING',
  'tj maxx': 'SHOPPING',
  'ross': 'SHOPPING',
  'dollar general': 'SHOPPING',
  'dollar tree': 'SHOPPING',
  'family dollar': 'SHOPPING',
  'cvs': 'SHOPPING',
  'walgreens': 'SHOPPING',
  'rite aid': 'SHOPPING',

  // Transportation
  'shell': 'TRANSPORTATION',
  'exxon': 'TRANSPORTATION',
  'chevron': 'TRANSPORTATION',
  'bp': 'TRANSPORTATION',
  'mobil': 'TRANSPORTATION',
  'speedway': 'TRANSPORTATION',
  'marathon': 'TRANSPORTATION',
  'valero': 'TRANSPORTATION',
  'uber': 'TRANSPORTATION',
  'lyft': 'TRANSPORTATION',

  // Entertainment
  'netflix': 'ENTERTAINMENT',
  'hulu': 'ENTERTAINMENT',
  'spotify': 'ENTERTAINMENT',
  'apple': 'ENTERTAINMENT',
  'disney+': 'ENTERTAINMENT',
  'hbo max': 'ENTERTAINMENT',
  'youtube': 'ENTERTAINMENT',
  'prime video': 'ENTERTAINMENT',
  'paramount+': 'ENTERTAINMENT',
  'peacock': 'ENTERTAINMENT',
  'amc theatres': 'ENTERTAINMENT',
  'regal cinemas': 'ENTERTAINMENT',
  'cinemark': 'ENTERTAINMENT',

  // Business
  'microsoft': 'BUSINESS',
  'google': 'BUSINESS',
  'adobe': 'BUSINESS',
  'dropbox': 'BUSINESS',
  'slack': 'BUSINESS',
  'zoom': 'BUSINESS',
  'godaddy': 'BUSINESS',
  'squarespace': 'BUSINESS',
  'wix': 'BUSINESS',

  // Healthcare
  'cvs pharmacy': 'HEALTHCARE',
  'walgreens pharmacy': 'HEALTHCARE',
  'rite aid pharmacy': 'HEALTHCARE',
  'quest diagnostics': 'HEALTHCARE',
  'labcorp': 'HEALTHCARE',
  'minute clinic': 'HEALTHCARE',
  'kaiser': 'HEALTHCARE',
  'united healthcare': 'HEALTHCARE',
  'anthem': 'HEALTHCARE',
  'cigna': 'HEALTHCARE',
  'aetna': 'HEALTHCARE',
}; 