import { AlertCircle } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";

interface DisclaimerBannerProps {
  variant?: "default" | "ai" | "investment" | "compact";
  className?: string;
}

export function DisclaimerBanner({ variant = "default", className }: DisclaimerBannerProps) {
  const getContent = () => {
    switch (variant) {
      case "ai":
        return {
          title: "AI-Powered Insights",
          description: "The insights and recommendations provided are generated by AI and should not be considered professional financial advice. Always consult with qualified financial advisors for important financial decisions."
        };
      case "investment":
        return {
          title: "Investment Disclaimer",
          description: "Past performance does not guarantee future results. Investment recommendations are for informational purposes only and should not be considered financial advice."
        };
      case "compact":
        return {
          title: "Notice",
          description: "AI-generated insights. Not financial advice."
        };
      default:
        return {
          title: "Important Notice",
          description: "This platform provides AI-driven financial insights but is not a substitute for professional financial advice. Always verify information and consult qualified professionals."
        };
    }
  };

  const content = getContent();

  return (
    <Alert className={`border-blue-500/20 bg-blue-500/5 ${className}`}>
      <AlertCircle className="h-4 w-4 text-blue-500" />
      <AlertTitle className="text-blue-500">{content.title}</AlertTitle>
      <AlertDescription className="text-blue-200/70">
        {content.description}
      </AlertDescription>
    </Alert>
  );
} 